# Generated by Django 3.2 on 2022-11-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalID', models.PositiveIntegerField()),
                ('birth_date', models.DateField()),
                ('government', models.CharField(choices=[(1, 'Cairo'), (2, 'Alexandria'), (3, 'Port Said'), (4, 'Suez'), (11, 'Damietta'), (12, 'Daqahliya'), (13, 'Sharqiya'), (14, 'Qalioubiya'), (15, 'Kafr El Sheikh'), (16, 'Gharbiya'), (17, 'Monofiya'), (18, 'Beheira'), (19, 'Ismailia'), (21, 'Giza'), (22, 'Bani Suef'), (23, 'Fayyoum'), (24, 'Minya'), (25, 'Assiut'), (26, 'Sohag'), (27, 'Qena'), (28, 'Aswan'), (29, 'Luxor'), (31, 'Red Sea'), (32, 'New Valley'), (33, 'Matrouh'), (34, 'North Sinai'), (35, 'South Sinai'), (88, 'Born Abroad')], max_length=2)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
