# Generated by Django 3.2 on 2022-11-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nationalID',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
