# Generated by Django 3.2 on 2022-11-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_person_nationalid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='millennium',
            new_name='century',
        ),
    ]
